// <auto-generated />
using System;
using Locker.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Locker.Migrations
{
    [DbContext(typeof(LockerDbContext))]
    partial class LockerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Locker.DatabaseContext.Model.Account", b =>
                {
                    b.Property<string>("Id_student")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Point");

                    b.Property<string>("Role");

                    b.HasKey("Id_student");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Locker.DatabaseContext.Model.Content", b =>
                {
                    b.Property<int>("Id_content")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("PlainText");

                    b.HasKey("Id_content");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Locker.DatabaseContext.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstNameEN");

                    b.Property<string>("FirstNameTH");

                    b.Property<string>("GenderCode");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsNotified");

                    b.Property<string>("LastNameEN");

                    b.Property<string>("LastNameTH");

                    b.Property<string>("Nickname");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("RoleCode");

                    b.Property<string>("StaffId");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Locker.DatabaseContext.Model.LockerMetadata", b =>
                {
                    b.Property<string>("Mac_address")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Location");

                    b.HasKey("Mac_address");

                    b.ToTable("LockerMetadatas");
                });

            modelBuilder.Entity("Locker.DatabaseContext.Model.MessageDetail", b =>
                {
                    b.Property<int>("Id_message")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("Id_contentRef");

                    b.Property<string>("Id_studentRef");

                    b.Property<bool>("IsShow");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id_message");

                    b.ToTable("MessageDetails");
                });

            modelBuilder.Entity("Locker.DatabaseContext.Model.Reservation", b =>
                {
                    b.Property<int>("Id_reserve")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("EndDay");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Id_locker");

                    b.Property<string>("Id_student");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("StartDay");

                    b.Property<DateTime>("StartTime");

                    b.Property<bool>("Status");

                    b.HasKey("Id_reserve");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Locker.DatabaseContext.Model.Vacancy", b =>
                {
                    b.Property<string>("Mac_addressRef");

                    b.Property<string>("No_vacancy");

                    b.Property<int>("Id_vacancy");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Size");

                    b.HasKey("Mac_addressRef", "No_vacancy");

                    b.HasAlternateKey("Id_vacancy");

                    b.ToTable("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
